name: build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Set up JDK 19
        uses: actions/setup-java@v1
        with: 
          java-version: 19
      - name: Run tests with Maven
        run: mvn -B test

