name: build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Set up JDK 19
        uses: actions/setup-java@v1
        with:
          java-version: 19

      - name: Set up MySQL 5.7
        uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: '5.7'
      - name:  Prepare MySQL database
        run: mysql -umessaging -h127.0.0.1 < sql/init.sql

      - name: Run tests with Maven
        run: mvn -B test
